### ISSUE TITLE
Team Designer/Coder pair.  Prototype layout.  Get your own STYLE, COLORS, FONTS; get your basic groove into your site.  Create these elements.  This should be consider CSS or <style> for your site.

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#10]
We added background photos and chose a color palate that would suit our page well. We have made a theme of black, gold, and white along with a rice themed background that fits our website, and arial+calibri font. All this can be seen on this page:

- [x] [About Page](https://github.com/AD1616/flask_portfolio/blob/main/templates/about.html)

Yash and I accept work on this issue

**Comment by Isaac-Le** [comment]
I choose and integrated the background photo
