### ISSUE TITLE
Individual Coding.   Review your home pages again.  Make sure you have a personal design or wireframe that can be linked to from page that shows design. 

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#12]
Individual Home pages:

- [x] [Sahil Home page code](https://github.com/AD1616/flask_portfolio/blob/main/templates/Sahil.html)

- [x] [Erik Home page code](https://github.com/AD1616/flask_portfolio/blob/main/templates/Erik.html)

- [x] [Yash Home page code](https://github.com/AD1616/flask_portfolio/blob/main/templates/Yash.html)

- [x] [Isaac Home page code](https://github.com/AD1616/flask_portfolio/blob/main/templates/Isaac.html)

We will continue to make our home pages more personalized.

**Comment by Isaac-Le** [comment]
I accept work on this issue
