### ISSUE TITLE
Individual Research

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#13]
[Isaac and Sahil](https://docs.google.com/document/d/1-79zrF_rkQSlD2ayyWv9OEqQAF3kZPOUrr91CwQUH5s/edit)

[Erik and Yash](https://docs.google.com/document/d/1iP8-gWius5-_VajB1pgc2nL83-qHCgv0LH-0-uFj4pI/edit)

- [x] [Group TPT 3 Notes on Collegeboard and Harvard videos](https://docs.google.com/document/d/1fi0Zj9yxSZaZkP6lQqXoL14BMwgHD4VMOBYDQ0LvwhM/edit)

Research will be added as we do more.

**Comment by Isaac-Le** [comment]
I accept work on this issue
