### ISSUE TITLE
Teacher Week 4 Review

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#21]

**Comment by tonyhieu** [comment]
Individual tangibles and projects look good. Each person contributing to their own piece of the website is good practice, and it helps to bring the project together at the end. 2/2 for all

I like the project vision you guys have, but you need more tickets regarding your back log and planning for future weeks. Tickets are super well made and thorough. 0.9/1

Your team vision looks good, and it's good that you all are contributing your own parts to the website. The design section is very well made with embeds and such. Hope to see your ideas take place! 2/2

Final grading: 4.9/5 for all

**Comment by tonyhieu** [comment]
Changed after Mr. M's grading: 4.75
