### ISSUE TITLE
Wire Frame

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#5]
Theme pages: [theme pages 1](https://docs.google.com/drawings/d/1blPXDeaPubER-gAHyGBngrtxeN-vLiY5WKN-2aqO8-Q/edit), [theme page 2](https://docs.google.com/drawings/d/1iUHZpTsHxTqLAXmsw7_yFhUrIjG1LG6v8OYxuNUdkGA/edit), [theme page 3](https://docs.google.com/drawings/d/1-ohIxvq5Q8XuaZxKGwjp4loVQkUf3HMt5p6ulrTQGek/edit?usp=sharing)
[About commit](https://github.com/AD1616/flask_portfolio/commit/7bc8001b626c0d76dc7c630535a43649da43591c)
[About page code](https://github.com/AD1616/flask_portfolio/blob/main/templates/about.html)

**Comment by Isaac-Le** [comment]
https://docs.google.com/drawings/d/1iUHZpTsHxTqLAXmsw7_yFhUrIjG1LG6v8OYxuNUdkGA/edit 
https://docs.google.com/drawings/d/1blPXDeaPubER-gAHyGBngrtxeN-vLiY5WKN-2aqO8-Q/edit
https://docs.google.com/drawings/d/1-ohIxvq5Q8XuaZxKGwjp4loVQkUf3HMt5p6ulrTQGek/edit
