### ISSUE TITLE
Week 7 Review

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#55]
Mortensen says 2/2 for planning.

**Comment by dtsivkovski** [comment]
### Sahil Samar's Score: 8/8

Commits:
- All of Sahil's commits are very complex and add new content to each commit. It is clear he has worked very hard on his color codes and signed addition/subtraction pages. His code is clear and laid out with comments to make it easy to understand.
Notes/Other Work:
- Sahil has completed his TPT and Collegeboard video notes on his [pair journal](https://docs.google.com/document/d/1rIoLDiSuxLC7XXiXv_x3-qoh1tNNXV--mmk_7Q-_QWs/edit), and has provided evidence of taking the [Collegeboard quiz and corrections](https://docs.google.com/document/d/1uKmnJZ_RvikCcN8kWjqz3_LSdzdYQhJJQXZzFWSu_AU/edit). Additionally, the [hackathon python file](https://github.com/AD1616/flask_portfolio/blob/main/templates/tt7Activity1.py) shows completion and understanding of lists and dictionaries.

**Comment by dtsivkovski** [comment]
### Overall individual scores: 
**8/8** - Sahil Samar
**8/8** - Erik Peterson
**8/8** - Isaac Le
**8/8** - Yash Shah

**Comment by Chom642** [comment]
Isaac Le

-Commits are clear and easy to read. Code also contains an appropriate level of complexity
-Got 6/6 on the College Board quizzes
-TPT notes were well organized and neatly done

Score: 8/8

**Comment by xXAASXx** [comment]
Yash Shah's Score: 8/8
Commits: The [unsigned and signed addition](https://github.com/AD1616/flask_portfolio/commit/fa47299bd43c34a9f2b33989f092b11c23e928af) page is done very well and efficiently with all the code looking nice and performing all its tasks.

Notes/Other Work:
Yash has completed his TPT and Collegeboard video notes on his pair journal, and has provided evidence of taking the Collegeboard quiz and corrections. Additionally, the hackathon python file shows completion and understanding of lists and dictionaries. Everything again is done nice and neat. WELL DONE!
