### ISSUE TITLE
Week 8 Review

### ISSUE THREAD

**Issue by AD1616** [AD1616/flask_portfolio#57]
Week 8 Team Score:
4.5 on presentation
3.25/3 for group for TPT and extra credit challenge

Total scores:

1. Erik: 7.75/8
2. Yash: 7.75/8
3. Isaac: 7.75/8
4.  Sahil: 7.75/8

**Comment by jm1021** [comment]
Review ticket in zoom
- [x] Time Box of Design/Issues/Features accomplishment in README.

1 minute of Project
- [ ] Presenting project/ideas
- [ ] Technical highlights
- [ ] Key features planned for N@tM project 

2 minute runtime
- [ ] Show running project
- [x] Mention anything that shows incorporation of mini lab technicals in project .25 extra
- [x] Runtime Feature 1
- [x] Runtime Feature 2
- [ ] Runtime Feature 3

Technical overview
- [x]  Technical Feature 1
- [x]  Technical Feature 2
 

- [ ] Be passionate about the technical, WOW factor.

Rice Quiz was intro and is somewhat of a hook. View and technical swap is showing integration of key ideas.

It is hard to see what is going to be next, introduction did not set us up.

**Comment by Archkitten** [comment]
mmm rice
A suggestion could be to improve the UI and theme of the website home page and rice quiz, right now it is just a blank white. Maybe add rice textures or a white pattern background?

**Comment by sanvi1855544** [comment]
I really liked your rice quiz. It is an interesting idea and from your runtime, it executes well (every question is unique).  Make sure your code has comments.

**Comment by kamyamah** [comment]
I liked the quiz it was complex and well done.

**Comment by Gabrielboudreau** [comment]
Quiz is interesting and works very well, the end quiz portion at the end is nice. Is there any way to simplify the code for the quiz as many elements seem slightly repetitive.

**Comment by WilliamDu22** [comment]
I love the quiz idea with the points. The code also looks very clean with the lines and they are easy to read. The page looks like it doesn't have much on it so maybe add a background or something else.

**Comment by rkaavya** [comment]
I really like your quiz and how you were able to change the button text and calculate a score at the end of your quiz.

**Comment by tangalice** [comment]
your UI is very interactive. I especially like how wrong answers were highlighted red and correct answers were highlighted green in your rice quiz. I also loved how there were live updates in your score for the rice quiz

**Comment by dtsivkovski** [comment]
I am very impressed with your integration of the multiple choice rice quiz, and it shows your understanding of lists and conditionals. One thing I would recommend is potentially optimizing the javascript code in the quiz so that you do not need so many lines of code.

**Comment by Tyler929** [comment]
I liked the Idea of the project; I've never encountered a website about only rice facts and fun games. I also believe the addition of the quiz was really cool, although it can be visually improved/the UI can easily be made to look better.

**Comment by David-Xie123** [comment]
The rice website is unique, though I'm not sure of the purpose of the website. May need to include that in the home page. The trivia questions and facts are nice and helps the viewers learn about them or simply test their understanding. You might be able to use web API's to get more facts and questions. Good job and nice presentation overall

**Comment by TimL1n** [comment]
I really liked how you made the quiz so that you can either answer and move on, or answer and fix your answer. The UI of the quiz is nice when it comes to getting feedback on your answer and moving to the next question, however I think it could have more color/pop to seem more significant. Same thing with the scavenger hunt. Overall, the quiz was an impressive demonstration of various skill but the UI details need some work.

**Comment by willcyber** [comment]
Your quizzes are very unique and interesting. Your rice facts is very interesting. I really like your homepage background. One suggestion I have is to add some kind of background or color on your rice quiz and scavenger hunt webpage to make it more visually appealing and interesting.

**Comment by ghost** [comment]
Things I liked:
- I liked the idea of providing a rice test score. The use of DOM for the quiz was unique. Also, I liked the easy to understand interface. 

Things to improve on:
- Maybe improve the background or center the design. I think the white background is a bit bland and you could use API to get more fun rice facts.

**Comment by kiannp44** [comment]
The website seems to have a very unique theme, rice. I really like the text fonts you guys put, they seem very appealing but I feel like there are too many different types of fonts, maybe keep the fonts more consistent.

**Comment by katiehickman** [comment]
I liked how you used "changing the DOM" when the score increases and how at the end of your quiz you have and "end quiz button" and a score report. For an improvement, I would add more style to the rice quiz page and add a background/different fonts.

**Comment by NathanManangan** [comment]
Highlights:
- I like the projects you have implemented into your site, and how they all relate to rice, which is an amazing food btw

Improvements:
- I think formatting your HTML pages to be more visually appealing, like instead of just a plain white page make it a color or picture for a background

**Comment by wangzi190** [comment]
I like your project idea! I also thought it was cool how you used the JS DOM and your knowledge on conditionals to create the quiz game on the site. Nice job on this

**Comment by Chom642** [comment]
I really liked the multiple choice quiz and how you used lists for the questions and points. I also liked the random rice facts page. However I think that the UI of both pages can be improved on.

**Comment by shreya-ahujaa** [comment]
I really liked how you added a quiz that also adds points when you answer the questions or when you reach the end of the quiz. I also liked how you explained the code behind the the things you made because it showed how you got there. For an improvement, I would say maybe add more style to the website, like adding a background to some pages.

**Comment by xXAASXx** [comment]
Things I like:
I like the way you guys implemented a quiz to your code as trivia questions are always a lot of fun.
Test Score was really cool.
Things to Improve On:
Usually at the end of a trivia there is more than just saying good job, what I think you guys can add is a prize or a pop up saying that you did amazing or bad.
I also think that you guys can make the website more appealing by adding different color or image backgrounds instead of just a white background everytime.

**Comment by DerekBokelman** [comment]
Positive:
I loved the quiz about rice. It was super interesting and unique.
I also really like the random rice fact generator.
The finishing page was also super cool.

Things to work on: I think you can add in some colors or backgrounds to further improve the website.

**Comment by isabelle926** [comment]
I really like the rice quiz and scavenger hunt!
Try using a more interesting layout to get more engagement

**Comment by Reinhardtlotter** [comment]
I like how user interactive the website is and hw much the user an do on it. One thing I might change is extend the scavenger hunt to have people explore the website more.

**Comment by tonyhieu** [comment]
The scavenger hunt is a really cool idea.  You should make it more intuitive (submitting the score with a small box at the bottom isn't obvious) for users to use.

**Comment by ellenjxu** [comment]
The execution of the quiz was really well done! It was really interactive and unique. One improvement could be to work on the colors and perhaps some pictures of rice.

**Comment by aidanywu** [comment]
The rice quiz was a really nice idea. Something you could improve on is to add a better overall style of the website, like the background and font family.

**Comment by Pitsco** [comment]
I loved how you included a quiz that awards points for correctly answering questions or reaching the conclusion of the quiz. I also liked how you detailed the coding behind the items you created since it demonstrated how you arrived at your conclusion. I think the website might be improved by adding more flair, such as a background to certain pages.

**Comment by VidhiKulkarni** [comment]
I liked the incorporation of the rice quiz. I also liked how you incorporated rice facts. The rice game was also good. I would recommend making the layout/background of the website look better.

**Comment by mahimak19** [comment]
Love the idea, very original. I like how you made the rice quiz with cool questions. I also like the random rice fact generator and your use of algorithms. Your home page is also really clean. Maybe an improvement is to incorporate some more interactive elements into your website.

**Comment by BrianZhang2016** [comment]
I like how you created a quiz on rice for your website. Additionally, the results of your quiz and amount of questions you got right. Furthermore, the random facts on rice is a nice touch to your website. One time you could work on is having some sort of background for the scavenger hunt.

**Comment by LindaLiu1202** [comment]
I like how unique and organized the website is. I also really like the random fact generator. Maybe you can add more information about the purpose of the website to your homepage or use a more interesting layout.

**Comment by Dylanluo05** [comment]
I liked the rice quiz you guys created on your website, and how it displays your score at the end. I also like the random rice fact generator. One thing I would do to improve your website is adding more to it, such as a rice quiz based on the rice facts.

**Comment by kar722** [comment]
I enjoyed the different games/quizzes you included to your website. Your website and presentation were very fun. I also enjoyed learning new things about rice with the rice fact generator. I think adding more backgrounds and just the aesthetic of the website could be improved.

**Comment by Nayanav** [comment]
The idea of the quizzes is really nice. I like how the button also changes to show "Submit" when you reach a certain point. The incorporation of API to your rice theme was really nice. One suggestion would be to maybe add animation elements to your quiz.
